// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkxSqJhq6DtLt5Dz4_YJcQbKNcPIgA__g',
    appId: '1:236436825228:web:25d49f5520749c1a9507a9',
    messagingSenderId: '236436825228',
    projectId: 'machine-task-fire',
    authDomain: 'machine-task-fire.firebaseapp.com',
    storageBucket: 'machine-task-fire.firebasestorage.app',
    measurementId: 'G-YPYX23K84V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9gLvkoDexiCPi5mpZIw4asfwFc6Nadg',
    appId: '1:236436825228:android:b848a3adfa9aa3709507a9',
    messagingSenderId: '236436825228',
    projectId: 'machine-task-fire',
    storageBucket: 'machine-task-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6oBI7Xwyd7pjiFE59bJJLpayleurjT1Q',
    appId: '1:236436825228:ios:1759d1ed89d25def9507a9',
    messagingSenderId: '236436825228',
    projectId: 'machine-task-fire',
    storageBucket: 'machine-task-fire.firebasestorage.app',
    iosBundleId: 'com.example.machineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6oBI7Xwyd7pjiFE59bJJLpayleurjT1Q',
    appId: '1:236436825228:ios:1759d1ed89d25def9507a9',
    messagingSenderId: '236436825228',
    projectId: 'machine-task-fire',
    storageBucket: 'machine-task-fire.firebasestorage.app',
    iosBundleId: 'com.example.machineTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkxSqJhq6DtLt5Dz4_YJcQbKNcPIgA__g',
    appId: '1:236436825228:web:2f1bff1101f6502a9507a9',
    messagingSenderId: '236436825228',
    projectId: 'machine-task-fire',
    authDomain: 'machine-task-fire.firebaseapp.com',
    storageBucket: 'machine-task-fire.firebasestorage.app',
    measurementId: 'G-2CPS8WGGWE',
  );
}
